const personagensOnePiece = [
    {
        nome: "Monkey D. Luffy",
        imagem: "/imgs/luffy.jpeg",
        habilidades: ["Haki", "Gomu Gomu no Mi", "Gear Second", "Gear Third", "Gear Fourth"],
        recompensa: "3.000.000.000 de Berries",
        características: "Extremamente otimista, teimoso, ama carne",
        afiliações: "Piratas do Chapéu de Palha, Supernovas",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Gomu Gomu no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Monkey_D._Luffy?so=search"
    },
    {
        nome: "Roronoa Zoro",
        imagem: "/imgs/zoro.jpeg",
        habilidades: ["Santoryu", "Haki", "Kinshiki"],
        recompensa: "1.111.000.000 de Berries",
        características: "Serio, orgulhoso, sonha em ser o melhor espadachim",
        afiliações: "Piratas do Chapéu de Palha",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Nenhuma",
        link: "https://onepiece.fandom.com/pt/wiki/Roronoa_Zoro?so=search"
    },
    {
        nome: "Nami",
        imagem: "/imgs/nami.jpeg",
        habilidades: "Clima-Tact, Navegação, Haki",
        recompensa: "366.000.000 de Berries",
        características: "Inteligente, astuta, ama dinheiro",
        afiliações: "Piratas do Chapéu de Palha",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Nenhuma",
        link: "https://onepiece.fandom.com/pt/wiki/Nami?so=search"
    },
    {
        nome: "Sanji",
        imagem: "/imgs/sanji.jpeg",
        habilidades: "Diable Jambe, Luta",
        recompensa: "1.032.000.000 de Berries",
        características: "Gentil com as mulheres, apaixonado por cozinhar",
        afiliações: "Piratas do Chapéu de Palha",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Nenhuma",
        link: "https://onepiece.fandom.com/pt/wiki/Usopp?so=search"
    },
    {
        nome: "Usopp",
        imagem: "/imgs/usopp.jpeg",
        habilidades: "Mentiras, Sling Shot, Haki",
        recompensa: "500.000.000 de Berries",
        características: "Medroso, mentiroso, mas corajoso quando necessário",
        afiliações: "Piratas do Chapéu de Palha",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Nenhuma",
        link: "https://onepiece.fandom.com/pt/wiki/Sanji?so=search"
    },
    {
        nome: "Tony Tony Chopper",
        imagem: "/imgs/chopper.jpeg",
        habilidades: "Transformação Zoan, Médico habilidoso, Comunicação com animais",
        recompensa: "1.000 Berries",
        características: "Rena com nariz azul, infantil, curioso, tem dificuldades com elogios, mas é leal e protetor com os amigos",
        afiliações: "Piratas do Chapéu de Palha",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Hito Hito no Mi (Fruta Humano-Humano)",
        link: "https://onepiece.fandom.com/pt/wiki/Tony_Tony_Chopper?so=search"
    },
    {
        nome: "Nico Robin",
        imagem: "/imgs/robin.jpeg",
        habilidades: "Hana Hana no Mi, Arqueologia",
        recompensa: "930.000.000 de Berries",
        características: "Calma, inteligente, busca a verdade sobre o Século Vazio",
        afiliações: "Piratas do Chapéu de Palha",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Hana Hana no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Nico_Robin?so=search"
    },
    {
        nome: "Franky",
        imagem: "/imgs/franky.jpeg",
        habilidades: "Construção naval, cyborg",
        recompensa: "394.000.000 de Berries",
        características: "Exuberante, amante de tecnologia",
        afiliações: "Piratas do Chapéu de Palha",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Nenhuma",
        link: "https://onepiece.fandom.com/pt/wiki/Franky?so=search"
    },
    {
        nome: "Brook",
        imagem: "/imgs/brook.jpeg",
        habilidades: "Música, espada, Yomi Yomi no Mi",
        recompensa: "383.000.000 de Berries",
        características: "Esqueleto, amante de mulheres, otimista",
        afiliações: "Piratas do Chapéu de Palha",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Yomi Yomi no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Brook?so=search"
    },
    {
        nome: "Jimbei",
        imagem: "/imgs/jimbe.jpeg",
        habilidades: "Karatê do Mar, Haki, mestre em artes marciais",
        recompensa: "1.100.000.000 de Berries",
        características: "Leal, forte, sábio",
        afiliações: "Piratas do Sol, Piratas do Chapéu de Palha",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: null,
        link: "https://onepiece.fandom.com/pt/wiki/Jinbe?so=search"
    },
    {
        nome: "Monkey D. Garp",
        imagem: "/imgs/garp.jpeg",
        habilidades: "Haki, Mestre em Haki, força física excepcional",
        recompensa: "Não possui",
        características: "Teimoso, forte, protetor",
        afiliações: "Marinha",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: null,
        link: "https://onepiece.fandom.com/pt/wiki/Monkey_D._Garp?so=search"
    },
    {
        nome: "Dracule Mihawk",
        imagem: "/imgs/mihawk.jpeg",
        habilidades: "Espadachim, Haki",
        recompensa: "3.590.000.000 de Berries",
        características: "Solitário, forte senso de justiça",
        afiliações: "Sete Guerreiros do Mar (antigo)",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Nenhuma",
        link: "https://onepiece.fandom.com/pt/wiki/Dracule_Mihawk?so=search"
    },
    {
        nome: "Donquixote Doflamingo",
        imagem: "/imgs/donquixote.jpeg",
        habilidades: "Ito Ito no Mi, Haki",
        recompensa: "340.000.000 de Berries",
        características: "Cruel, manipulador, ambicioso",
        afiliações: "Sete Guerreiros do Mar (antigo)",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Ito Ito no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Donquixote_Doflamingo?so=search"
    },
    {
        nome: "Edward Newgate (Whitebeard)",
        imagem: "/imgs/barba-branca.jpeg",
        habilidades: "Gura Gura no Mi, Haki, força sobre-humana",
        recompensa: "5.046.000.000 de Berries",
        características: "Forte, justo, protetor",
        afiliações: "Piratas do Barba Branca",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Gura Gura no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Edward_Newgate?so=search"
    },
    {
        nome: "Marshall D. Teach (Blackbeard)",
        imagem: "/imgs/barba-negra.jpeg",
        habilidades: "Yami Yami no Mi, Gura Gura no Mi, Haki",
        recompensa: "3.996.000.000 de Berries",
        características: "Ambicioso, cruel, manipulador",
        afiliações: "Piratas do Barba Negra",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Yami Yami no Mi, Gura Gura no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Marshall_D._Teach?so=search"
    },
    {
        nome: "Boa Hancock",
        imagem: "/imgs/boa-hancock.jpeg",
        habilidades: "Mero Mero no Mi, Haki, beleza irresistível",
        recompensa: "1.659.000.000 de Berries",
        características: "Orgulhosa, apaixonada, vaidosa",
        afiliações: "Piratas de Kuja",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Mero Mero no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Boa_Hancock?so=search"
    },
    {
        nome: "Portgas D. Ace",
        imagem: "/imgs/ace.jpeg",
        habilidades: "Mera Mera no Mi, Haki",
        recompensa: "550.000.000 de Berries",
        características: "Quente, impulsivo, leal",
        afiliações: "Segunda Divisão dos Piratas do Barba Branca",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Mera Mera no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Portgas_D._Ace?so=search"
    },
    {
        nome: "Trafalgar D. Water Law",
        imagem: "/imgs/law.jpeg",
        habilidades: "Ope Ope no Mi, Haki, cirurgião",
        recompensa: "3.000.000.000 de Berries",
        características: "Inteligente, calculista, frio",
        afiliações: "Piratas do Heart",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Ope Ope no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Trafalgar_D._Water_Law?so=search"
    },
    {
        nome: "Eustass Kid",
        imagem: "/imgs/kid.jpeg",
        habilidades: "Haki, força física excepcional, habilidades com armas",
        recompensa: "3.000.000.000 de Berries",
        características: "Orgulhoso, rival de Luffy, violento",
        afiliações: "Piratas Kid",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: null,
        link: "https://onepiece.fandom.com/pt/wiki/Eustass_Kid?so=search"
    },
    {
        nome: "Charlotte Katakuri",
        imagem: "/imgs/katakuri.jpeg",
        habilidades: "Mochi Mochi no Mi, Haki, observação do futuro",
        recompensa: "1.057.000.000 de Berries",
        características: "Calmo, inteligente, forte",
        afiliações: "Piratas da Big Mom",
        aparicoes: "Mangá, Anime",
        akumaNoMi: "Mochi Mochi no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Charlotte_Katakuri?so=search"
    },
    {
        nome: "Sabo",
        imagem: "/imgs/sabo.jpeg",
        habilidades: "Mera Mera no Mi, Haki, mestre em artes marciais",
        recompensa: "602.000.000 de Berries",
        características: "Quente, leal, protetor",
        afiliações: "Exército Revolucionário",
        aparicoes: "Mangá, Anime",
        akumaNoMi: "Mera Mera no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Sabo?so=search"
    },
    {
        nome: "Kaido",
        imagem: "/imgs/kaido.jpeg",
        habilidades: "Transformação em dragão (Zoan Mítica), Haki do Conquistador, imensa resistência e força",
        recompensa: "4.611.100.000 Berries",
        características: "Extremamente forte, busca uma morte gloriosa, tirano cruel",
        afiliações: "Piratas das Feras",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Uo Uo no Mi, Modelo: Dragão Azul",
        link: "https://onepiece.fandom.com/pt/wiki/Kaidou?so=search"
    },
    {
        nome: "Big Mom (Charlotte Linlin)",
        imagem: "/imgs/big-mom.jpeg",
        habilidades: "Soru Soru no Mi, manipulação de almas, Haki",
        recompensa: "4.388.000.000 Berries",
        características: "Grande apetite, controladora, extremamente poderosa",
        afiliações: "Piratas da Big Mom",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Soru Soru no Mi",
        link: "https://onepiece.fandom.com/pt/wiki/Charlotte_Linlin?so=search"
    },
    {
        nome: "Monkey D. Dragon",
        imagem: "/imgs/dragon.jpeg",
        habilidades: "Possivelmente usuário de Haki, misterioso poder relacionado ao vento",
        recompensa: "Desconhecida",
        características: "Líder dos Revolucionários, sério e determinado",
        afiliações: "Exército Revolucionário",
        aparicoes: "Mangá, Anime",
        akumaNoMi: "Desconhecida",
        link: "https://onepiece.fandom.com/pt/wiki/Monkey_D._Dragon?so=search"
    },
    {
        nome: "Shanks",
        imagem: "/imgs/shanks.jpeg",
        habilidades: "Haki do Conquistador supremo, espadachim habilidoso",
        recompensa: "4.048.900.000 Berries",
        características: "Calmo, sábio, carismático",
        afiliações: "Piratas do Ruivo",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Nenhuma",
        link: "https://onepiece.fandom.com/pt/wiki/Shanks?so=search"
    },
    {
        nome: "Gol D. Roger",
        imagem: "/imgs/gold-roger.jpeg",
        habilidades: "Haki do Conquistador, espadachim",
        recompensa: "5.564.800.000 Berries",
        características: "Aventureiro, determinado, líder nato",
        afiliações: "Piratas de Roger",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Nenhuma",
        link: "https://onepiece.fandom.com/pt/wiki/Gol_D._Roger?so=search"
    },
    {
        nome: "JoyBoy",
        imagem: "/imgs/joy-boy.jpeg",
        habilidades: "Desconhecidas, possivelmente uma figura lendária",
        recompensa: "Desconhecida",
        características: "Figura misteriosa do passado",
        afiliações: "Desconhecida",
        aparicoes: "Mangá, Anime",
        akumaNoMi: "Desconhecida",
        link: "https://onepiece.fandom.com/pt/wiki/Joy_Boy?so=search"
    },
    {
        nome: "Kozuki Oden",
        imagem: "/imgs/oden.jpeg",
        habilidades: "Haki do Conquistador, mestre em espadas",
        recompensa: "Desconhecida",
        características: "Orgulhoso, destemido, aventureiro",
        afiliações: "Clã Kozuki, Piratas de Barba Branca, Piratas de Roger",
        aparicoes: "Mangá, Anime, Filmes",
        akumaNoMi: "Nenhuma",
        link: "https://onepiece.fandom.com/pt/wiki/Kozuki_Oden?so=search"
    }
];